{
  "_from": "express-catch-errors",
  "_id": "express-catch-errors@0.1.0",
  "_inBundle": false,
  "_integrity": "sha512-d50uMDjwj0eNIhXtutYx8OaFFLhnHIO1rxT+XSnVjHoX+5TC3wCdICYve1psMwN78Jo7wtDWvzmsASjW+17RRw==",
  "_location": "/express-catch-errors",
  "_phantomChildren": {},
  "_requested": {
    "type": "tag",
    "registry": true,
    "raw": "express-catch-errors",
    "name": "express-catch-errors",
    "escapedName": "express-catch-errors",
    "rawSpec": "",
    "saveSpec": null,
    "fetchSpec": "latest"
  },
  "_requiredBy": [
    "#USER",
    "/"
  ],
  "_resolved": "https://registry.npmjs.org/express-catch-errors/-/express-catch-errors-0.1.0.tgz",
  "_shasum": "8231eb7d4b3490fc8fbf0e87e222906e5401b67b",
  "_spec": "express-catch-errors",
  "_where": "C:\\Users\\anton\\Documents\\skripsi\\New System\\Hospital",
  "author": {
    "name": "Roberto Achar",
    "email": "robertoachar@gmail.com"
  },
  "bugs": {
    "url": "https://github.com/robertoachar/express-catch-errors/issues"
  },
  "bundleDependencies": false,
  "dependencies": {},
  "deprecated": false,
  "description": "A high-order function to catch errors from promises.",
  "devDependencies": {
    "eslint": "4.7.2"
  },
  "files": [
    "src"
  ],
  "homepage": "https://github.com/robertoachar/express-catch-errors#readme",
  "keywords": [
    "node",
    "express",
    "middleware",
    "promises",
    "async",
    "await",
    "catch",
    "error",
    "errors"
  ],
  "license": "MIT",
  "main": "src/index.js",
  "name": "express-catch-errors",
  "repository": {
    "type": "git",
    "url": "git+https://github.com/robertoachar/express-catch-errors.git"
  },
  "scripts": {
    "lint": "eslint src/**/*.js"
  },
  "version": "0.1.0"
}
